import BookForm from '@/src/components/Book/BookForm'
import { IBook } from '@/src/interfaces'
import React from 'react'

export const metadata = {
  title: 'Nuevo Libro',
  description: 'Generated by create next app',
}
const book = {
  title: '',
  author: '',
  publisher: '',
  description: '',
  pageCount: 0,
  language: '',
  price: 0,
  inventory: 0,
  image: '',
  user: '',
}
function Book() {
  return <BookForm book={book} edit={false} />
}

export default Book
