// import BookList from '@/src/components/Book/BookList'
import LoginForm from '@/src/components/User/Login/LoginForm'

export const metadata = {
  title: 'Bienvenido! Registra toso tus libros',
  description: 'Generated by create next app',
}

const Login = () => {
  return <LoginForm />
}
export default Login
