import RegisterForm from '@/src/components/User/Register/Register'

export const metadata = {
  title: 'Registrate y guarda todos tus libros!',
  description: 'Generated by create next app',
}

function Register() {
  return <RegisterForm />
}

export default Register
